version: '3.9'

services:
  # app:
  #   build: ./
  #   networks:
  #     - products-csv
  #   ports:
  #     - 8010:8010
  #   depends_on:
  #     - redis

  redis:
    image: "redis:alpine"
    ports:
     - "6379:6379"
    environment:
     - REDIS_REPLICATION_MODE=master
    networks:
      - products-csv

networks:
  products-csv: